main:
  # Introduce
  - name: Introduce
    url: people
    weight: 200
  - parent: Introduce
    name: Developer Profile
    url: /author/최홍석/
    weight: 210

  # Achievement
  - name: Achievement
    url: Awards
    weight: 300
  - parent: Achievement
    name: Qualifications
    url: /Qualifications/  # URL을 절대 경로로 수정
    weight: 310
  - parent: Achievement
    name: awards
    url: /awards/
    weight: 320


  # 프로젝트
  - name: Projects
    url: projects/
    weight: 330

  # 알림 메뉴
  - name: Security Info
    url: post
    weight: 600
  - parent: Updates
    name: Notifications
    url: notification
    weight: 610
  - parent: Updates
    name: News
    url: post
    weight: 620
  - parent: Updates
    name: Events
    url: event
    weight: 630

  # Info
  - name: Information
    url: information
    weight: 800
  - parent: Information
    name: About Me
    url: about
    weight: 810
  - parent: Information
    name: Contact
    url: contact
    weight: 820