main:
  # Introduce
  - name: Introduce
    url: people
    weight: 200
  - parent: Introduce
    name: Developer Profile
    url: /author/최홍석/
    weight: 210

  # Achievement
  - name: Achievement
    url: Qualifications
    weight: 300
  - parent: Achievement
    name: Qualifications
    url: Qualifications
    weight: 310
  - parent: Achievement
    name: Awards
    url: Awards
    weight: 320

  # 캠퍼스 생활 메뉴
  - name: University Life
    url: publication
    weight: 330
  - parent: University Life
    name: Achievements
    url: /Campus Life/Awards/
    weight: 340
  - parent: University Life
    name: Activities
    url: /Campus Life/Activities/
    weight: 350

  # 알림 메뉴
  - name: Updates
    url: post
    weight: 600
  - parent: Updates
    name: Notifications
    url: notification
    weight: 610
  - parent: Updates
    name: News
    url: post
    weight: 620
  - parent: Updates
    name: Events
    url: event
    weight: 630

  # Info
  - name: Information
    url: information
    weight: 800
  - parent: Information
    name: About Me
    url: about
    weight: 810
  - parent: Info
    name: Contact
    url: contact
    weight: 820