# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  theme_day: custom
  theme_night: custom
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: '최홍석의 보안 연구소'
    description: '전북대학교 컴퓨터공학부 최홍석의 동네 보안 연구소입니다.'
    twitter: 'GetResearchDev'
    keywords: ['전북대학교', '컴퓨터공학', '보안', '클라우드', '네트워크', '전북대 최홍석', '전북대학교 최홍석', 'DevSecOps']
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: 'vgPFyOxWQ7-82UPbhHKuItHNg1K7sXo8BuS5W5CLy1c'
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false

# Site footer

footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/ChatHongPT/JBNU_HONGSEOK.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: true
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15
  

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa

# Personal information

name: 최홍석
role: 학생
organization: 전북대학교 IT정보공학과
organization_url: 'https://csai.jbnu.ac.kr/csai/index.do'
email: 'suk924600@naver.com'