name = "Research Group"
license = "MIT"
licenselink = "https://github.com/wowchemy/starter-hugo-research-group/blob/main/LICENSE.md"
description = "The **Research Group Template** empowers your research group to easily create a beautiful website with a stunning homepage, news, academic publications, events, team profiles, and a contact form."
homepage = "https://github.com/wowchemy/starter-hugo-research-group"
demosite = "https://research-group.netlify.app/"
tags = ["academic",
        "university",
        "research",
        "publications",
        "widgets",
        "portfolio",
        "responsive",
        "clean",
        "company",
        "blog",
        "events",
        "minimal",
        "light",
        "dark",
        "multilingual",
        "landing page",
        "contact form",
        "mobile",
        "search",
        "presentation",
        "simple",
        "minimalist",
        "starter",
        "modern",
        "one page",
        "customizable",
        "technical",
        "slide"
        ]
features = ["page builder", "widgets", "themes", "search", "research publication system", "filterable portfolio",
            "blog", "create courses", "talks", "events", "slides", "gallery", "contact form"]

[author]
  name = "George Cushen"
  homepage = "https://georgecushen.com"

[light]
  # Primary
  primary = "#2962ff"

  # Menu
  menu_primary = "rgb(247, 250, 252)"
  menu_text = "#34495e"
  menu_text_active = "#2962ff"
  menu_title = "#2b2b2b"

  # Home sections
  home_section_odd = "rgb(247, 250, 252)"
  home_section_even = "rgb(247, 250, 252)"

[dark]
  primary = "#bbdefb"
  link = "#bbdefb"
  link_hover = "#bbdefb"
  background = "rgb(26, 32, 44)"
  home_section_odd = "rgb(26, 32, 44)"
  home_section_even = "rgb(26, 32, 44)"
  menu_primary = "rgb(26, 32, 44)"
